Amazon Cognito configuraton  and installation
DecisiveAI/mdai-docs pull request #6
Opened 2024-03-11 16:03 UTC by s0b01ev

2024-03-11 16:46 UTC, o11yguru requested changes
One small change

2024-03-11 16:46 UTC, o11yguru commented on src/install/aws/ui-auth.md
> +The only manual step required is a user(s) creation.
Can we link to docs here? The less we write out steps for a service/tool we don't support the better. If they change UI, we'd have to maintain

2024-03-11 18:46 UTC, s0b01ev commented on src/install/aws/ui-auth.md
> +The only manual step required is a user(s) creation.
changed

2024-03-13 15:46 UTC, o11yguru submitted a review, later dismissed

2024-03-13 20:09 UTC, o11yguru approved these changes

2024-03-13 20:09 UTC, merged